server:
  port: 9999
spring:
  datasource:
    url: jdbc:h2:file:./deseri/cache/graphdb;MODE=MySQL;LOCK_MODE=3
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/jvd?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #    username: root
  #    password: 0int*me=NULL
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password: password
      database: neo4j
